# fly.toml app configuration file generated for laclipasa-backend on 2025-03-07T19:22:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'laclipasa-backend'
primary_region = 'mad'

[build]

[env]
APP_ENV = 'prod'
PORT = '8180'

[http_service]
internal_port = 8180
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '256MB'
cpu_kind = 'shared'
cpus = 1
