model:
  package: testclient
  filename: internal/gql/testclient/models.go
client:
  package: testclient
  filename: internal/gql/testclient/graphclient.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  ID:
    model:
      - github.com/caliecode/la-clipasa/internal/ent/schema/uuidgql.UUID
  # JSON:
  #   model:
  #     - github.com/theopenlane/entx.RawMessage
  #     - github.com/theopenlane/core/internal/ent/customtypes.JSONObject
  Address:
    model:
      - github.com/theopenlane/core/pkg/models.Address
schema: ["internal/gql/schema/*.graphql"]
query: ["internal/gql/testquery/*.graphql"]
generate:
  clientV2: true
  clientInterfaceName: "TestGraphClient"
  query: false
  mutation: false
