// Code generated by "project". DO NOT EDIT.

/// <reference types="vite/client" />

interface ImportMetaEnv {
  readonly TESTING: string
  readonly VITE_APP_ENV: string
  readonly VITE_DOMAIN: string
  readonly VITE_API_VERSION: string
  readonly VITE_REVERSE_PROXY_API_PREFIX: string
  readonly VITE_API_PORT: string
  readonly VITE_FRONTEND_PORT: string
  readonly VITE_BUILD_VERSION: string
  readonly VITE_LOGIN_COOKIE_KEY: string
  readonly VITE_AUTH_SERVER_UI_PROFILE: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
