// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package testclient

import (
	"context"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/caliecode/la-clipasa/internal/ent/generated/postcategory"
	"github.com/google/uuid"
)

type TestGraphClient interface {
	CreatePostMutation(ctx context.Context, input CreatePostInput, interceptors ...clientv2.RequestInterceptor) (*CreatePostMutation, error)
	CreatePostWithCategoriesMutation(ctx context.Context, input CreatePostWithCategoriesInput, interceptors ...clientv2.RequestInterceptor) (*CreatePostWithCategoriesMutation, error)
	UpdatePostMutation(ctx context.Context, id uuid.UUID, input UpdatePostInput, interceptors ...clientv2.RequestInterceptor) (*UpdatePostMutation, error)
	DeletePostMutation(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*DeletePostMutation, error)
	RestorePostMutation(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*RestorePostMutation, error)
	GetPostsQuery(ctx context.Context, first *int64, after *string, last *int64, before *string, where *PostWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetPostsQuery, error)
	GetAllRefreshTokens(ctx context.Context, first *int64, after *string, last *int64, before *string, where *RefreshTokenWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetAllRefreshTokens, error)
	DeleteRefreshToken(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*DeleteRefreshToken, error)
	Me(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Me, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli clientv2.HttpClient, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) TestGraphClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type PostFields struct {
	ID                uuid.UUID                "json:\"id\" graphql:\"id\""
	Title             string                   "json:\"title\" graphql:\"title\""
	Link              string                   "json:\"link\" graphql:\"link\""
	Content           *string                  "json:\"content,omitempty\" graphql:\"content\""
	ModerationComment *string                  "json:\"moderationComment,omitempty\" graphql:\"moderationComment\""
	IsModerated       bool                     "json:\"isModerated\" graphql:\"isModerated\""
	ModeratedAt       *time.Time               "json:\"moderatedAt,omitempty\" graphql:\"moderatedAt\""
	DeletedAt         *time.Time               "json:\"deletedAt,omitempty\" graphql:\"deletedAt\""
	Owner             PostFields_Owner         "json:\"owner\" graphql:\"owner\""
	Categories        []*PostFields_Categories "json:\"categories,omitempty\" graphql:\"categories\""
}

func (t *PostFields) GetID() *uuid.UUID {
	if t == nil {
		t = &PostFields{}
	}
	return &t.ID
}
func (t *PostFields) GetTitle() string {
	if t == nil {
		t = &PostFields{}
	}
	return t.Title
}
func (t *PostFields) GetLink() string {
	if t == nil {
		t = &PostFields{}
	}
	return t.Link
}
func (t *PostFields) GetContent() *string {
	if t == nil {
		t = &PostFields{}
	}
	return t.Content
}
func (t *PostFields) GetModerationComment() *string {
	if t == nil {
		t = &PostFields{}
	}
	return t.ModerationComment
}
func (t *PostFields) GetIsModerated() bool {
	if t == nil {
		t = &PostFields{}
	}
	return t.IsModerated
}
func (t *PostFields) GetModeratedAt() *time.Time {
	if t == nil {
		t = &PostFields{}
	}
	return t.ModeratedAt
}
func (t *PostFields) GetDeletedAt() *time.Time {
	if t == nil {
		t = &PostFields{}
	}
	return t.DeletedAt
}
func (t *PostFields) GetOwner() *PostFields_Owner {
	if t == nil {
		t = &PostFields{}
	}
	return &t.Owner
}
func (t *PostFields) GetCategories() []*PostFields_Categories {
	if t == nil {
		t = &PostFields{}
	}
	return t.Categories
}

type PostConnectionFields struct {
	TotalCount int64                         "json:\"totalCount\" graphql:\"totalCount\""
	Edges      []*PostConnectionFields_Edges "json:\"edges,omitempty\" graphql:\"edges\""
}

func (t *PostConnectionFields) GetTotalCount() int64 {
	if t == nil {
		t = &PostConnectionFields{}
	}
	return t.TotalCount
}
func (t *PostConnectionFields) GetEdges() []*PostConnectionFields_Edges {
	if t == nil {
		t = &PostConnectionFields{}
	}
	return t.Edges
}

type RefreshTokenFields struct {
	ID        uuid.UUID "json:\"id\" graphql:\"id\""
	CreatedAt time.Time "json:\"createdAt\" graphql:\"createdAt\""
	UpdatedAt time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	ExpiresAt time.Time "json:\"expiresAt\" graphql:\"expiresAt\""
	Revoked   bool      "json:\"revoked\" graphql:\"revoked\""
	IPAddress *string   "json:\"ipAddress,omitempty\" graphql:\"ipAddress\""
	UserAgent *string   "json:\"userAgent,omitempty\" graphql:\"userAgent\""
}

func (t *RefreshTokenFields) GetID() *uuid.UUID {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return &t.ID
}
func (t *RefreshTokenFields) GetCreatedAt() *time.Time {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return &t.CreatedAt
}
func (t *RefreshTokenFields) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return &t.UpdatedAt
}
func (t *RefreshTokenFields) GetExpiresAt() *time.Time {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return &t.ExpiresAt
}
func (t *RefreshTokenFields) GetRevoked() bool {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return t.Revoked
}
func (t *RefreshTokenFields) GetIPAddress() *string {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return t.IPAddress
}
func (t *RefreshTokenFields) GetUserAgent() *string {
	if t == nil {
		t = &RefreshTokenFields{}
	}
	return t.UserAgent
}

type RefreshTokenConnectionFields struct {
	TotalCount int64                                 "json:\"totalCount\" graphql:\"totalCount\""
	PageInfo   RefreshTokenConnectionFields_PageInfo "json:\"pageInfo\" graphql:\"pageInfo\""
	Edges      []*RefreshTokenConnectionFields_Edges "json:\"edges,omitempty\" graphql:\"edges\""
}

func (t *RefreshTokenConnectionFields) GetTotalCount() int64 {
	if t == nil {
		t = &RefreshTokenConnectionFields{}
	}
	return t.TotalCount
}
func (t *RefreshTokenConnectionFields) GetPageInfo() *RefreshTokenConnectionFields_PageInfo {
	if t == nil {
		t = &RefreshTokenConnectionFields{}
	}
	return &t.PageInfo
}
func (t *RefreshTokenConnectionFields) GetEdges() []*RefreshTokenConnectionFields_Edges {
	if t == nil {
		t = &RefreshTokenConnectionFields{}
	}
	return t.Edges
}

type PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &PostFields_Owner{}
	}
	return &t.ID
}

type PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &PostFields_Categories{}
	}
	return &t.Category
}
func (t *PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &PostFields_Categories{}
	}
	return &t.ID
}

type PostConnectionFields_Edges_Node_PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *PostConnectionFields_Edges_Node_PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &PostConnectionFields_Edges_Node_PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *PostConnectionFields_Edges_Node_PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &PostConnectionFields_Edges_Node_PostFields_Owner{}
	}
	return &t.ID
}

type PostConnectionFields_Edges_Node_PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *PostConnectionFields_Edges_Node_PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &PostConnectionFields_Edges_Node_PostFields_Categories{}
	}
	return &t.Category
}
func (t *PostConnectionFields_Edges_Node_PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &PostConnectionFields_Edges_Node_PostFields_Categories{}
	}
	return &t.ID
}

type PostConnectionFields_Edges struct {
	Node *PostFields "json:\"node,omitempty\" graphql:\"node\""
}

func (t *PostConnectionFields_Edges) GetNode() *PostFields {
	if t == nil {
		t = &PostConnectionFields_Edges{}
	}
	return t.Node
}

type RefreshTokenConnectionFields_PageInfo struct {
	EndCursor       *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage     bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
	HasPreviousPage bool    "json:\"hasPreviousPage\" graphql:\"hasPreviousPage\""
	StartCursor     *string "json:\"startCursor,omitempty\" graphql:\"startCursor\""
}

func (t *RefreshTokenConnectionFields_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &RefreshTokenConnectionFields_PageInfo{}
	}
	return t.EndCursor
}
func (t *RefreshTokenConnectionFields_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &RefreshTokenConnectionFields_PageInfo{}
	}
	return t.HasNextPage
}
func (t *RefreshTokenConnectionFields_PageInfo) GetHasPreviousPage() bool {
	if t == nil {
		t = &RefreshTokenConnectionFields_PageInfo{}
	}
	return t.HasPreviousPage
}
func (t *RefreshTokenConnectionFields_PageInfo) GetStartCursor() *string {
	if t == nil {
		t = &RefreshTokenConnectionFields_PageInfo{}
	}
	return t.StartCursor
}

type RefreshTokenConnectionFields_Edges struct {
	Node *RefreshTokenFields "json:\"node,omitempty\" graphql:\"node\""
}

func (t *RefreshTokenConnectionFields_Edges) GetNode() *RefreshTokenFields {
	if t == nil {
		t = &RefreshTokenConnectionFields_Edges{}
	}
	return t.Node
}

type CreatePostMutation_CreatePost_Post_PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *CreatePostMutation_CreatePost_Post_PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &CreatePostMutation_CreatePost_Post_PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *CreatePostMutation_CreatePost_Post_PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &CreatePostMutation_CreatePost_Post_PostFields_Owner{}
	}
	return &t.ID
}

type CreatePostMutation_CreatePost_Post_PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *CreatePostMutation_CreatePost_Post_PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &CreatePostMutation_CreatePost_Post_PostFields_Categories{}
	}
	return &t.Category
}
func (t *CreatePostMutation_CreatePost_Post_PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &CreatePostMutation_CreatePost_Post_PostFields_Categories{}
	}
	return &t.ID
}

type CreatePostMutation_CreatePost struct {
	Post *PostFields "json:\"post\" graphql:\"post\""
}

func (t *CreatePostMutation_CreatePost) GetPost() *PostFields {
	if t == nil {
		t = &CreatePostMutation_CreatePost{}
	}
	return t.Post
}

type CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Owner{}
	}
	return &t.ID
}

type CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Categories{}
	}
	return &t.Category
}
func (t *CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &CreatePostWithCategoriesMutation_CreatePostWithCategories_Post_PostFields_Categories{}
	}
	return &t.ID
}

type CreatePostWithCategoriesMutation_CreatePostWithCategories struct {
	Post *PostFields "json:\"post\" graphql:\"post\""
}

func (t *CreatePostWithCategoriesMutation_CreatePostWithCategories) GetPost() *PostFields {
	if t == nil {
		t = &CreatePostWithCategoriesMutation_CreatePostWithCategories{}
	}
	return t.Post
}

type UpdatePostMutation_UpdatePost_Post_PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *UpdatePostMutation_UpdatePost_Post_PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &UpdatePostMutation_UpdatePost_Post_PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *UpdatePostMutation_UpdatePost_Post_PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &UpdatePostMutation_UpdatePost_Post_PostFields_Owner{}
	}
	return &t.ID
}

type UpdatePostMutation_UpdatePost_Post_PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *UpdatePostMutation_UpdatePost_Post_PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &UpdatePostMutation_UpdatePost_Post_PostFields_Categories{}
	}
	return &t.Category
}
func (t *UpdatePostMutation_UpdatePost_Post_PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &UpdatePostMutation_UpdatePost_Post_PostFields_Categories{}
	}
	return &t.ID
}

type UpdatePostMutation_UpdatePost struct {
	Post *PostFields "json:\"post\" graphql:\"post\""
}

func (t *UpdatePostMutation_UpdatePost) GetPost() *PostFields {
	if t == nil {
		t = &UpdatePostMutation_UpdatePost{}
	}
	return t.Post
}

type DeletePostMutation_DeletePost struct {
	DeletedID uuid.UUID "json:\"deletedID\" graphql:\"deletedID\""
}

func (t *DeletePostMutation_DeletePost) GetDeletedID() *uuid.UUID {
	if t == nil {
		t = &DeletePostMutation_DeletePost{}
	}
	return &t.DeletedID
}

type GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Owner struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Owner) GetDisplayName() string {
	if t == nil {
		t = &GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Owner{}
	}
	return t.DisplayName
}
func (t *GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Owner) GetID() *uuid.UUID {
	if t == nil {
		t = &GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Owner{}
	}
	return &t.ID
}

type GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Categories struct {
	Category postcategory.Category "json:\"category\" graphql:\"category\""
	ID       uuid.UUID             "json:\"id\" graphql:\"id\""
}

func (t *GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Categories) GetCategory() *postcategory.Category {
	if t == nil {
		t = &GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Categories{}
	}
	return &t.Category
}
func (t *GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Categories) GetID() *uuid.UUID {
	if t == nil {
		t = &GetPostsQuery_Posts_PostConnectionFields_Edges_Node_PostFields_Categories{}
	}
	return &t.ID
}

type GetPostsQuery_Posts_PostConnectionFields_Edges struct {
	Node *PostFields "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetPostsQuery_Posts_PostConnectionFields_Edges) GetNode() *PostFields {
	if t == nil {
		t = &GetPostsQuery_Posts_PostConnectionFields_Edges{}
	}
	return t.Node
}

type GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo struct {
	EndCursor       *string "json:\"endCursor,omitempty\" graphql:\"endCursor\""
	HasNextPage     bool    "json:\"hasNextPage\" graphql:\"hasNextPage\""
	HasPreviousPage bool    "json:\"hasPreviousPage\" graphql:\"hasPreviousPage\""
	StartCursor     *string "json:\"startCursor,omitempty\" graphql:\"startCursor\""
}

func (t *GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo) GetEndCursor() *string {
	if t == nil {
		t = &GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo{}
	}
	return t.EndCursor
}
func (t *GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo) GetHasNextPage() bool {
	if t == nil {
		t = &GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo{}
	}
	return t.HasNextPage
}
func (t *GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo) GetHasPreviousPage() bool {
	if t == nil {
		t = &GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo{}
	}
	return t.HasPreviousPage
}
func (t *GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo) GetStartCursor() *string {
	if t == nil {
		t = &GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_PageInfo{}
	}
	return t.StartCursor
}

type GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_Edges struct {
	Node *RefreshTokenFields "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_Edges) GetNode() *RefreshTokenFields {
	if t == nil {
		t = &GetAllRefreshTokens_RefreshTokens_RefreshTokenConnectionFields_Edges{}
	}
	return t.Node
}

type DeleteRefreshToken_DeleteRefreshToken struct {
	DeletedID uuid.UUID "json:\"deletedID\" graphql:\"deletedID\""
}

func (t *DeleteRefreshToken_DeleteRefreshToken) GetDeletedID() *uuid.UUID {
	if t == nil {
		t = &DeleteRefreshToken_DeleteRefreshToken{}
	}
	return &t.DeletedID
}

type Me_Me struct {
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	ID          uuid.UUID "json:\"id\" graphql:\"id\""
}

func (t *Me_Me) GetDisplayName() string {
	if t == nil {
		t = &Me_Me{}
	}
	return t.DisplayName
}
func (t *Me_Me) GetID() *uuid.UUID {
	if t == nil {
		t = &Me_Me{}
	}
	return &t.ID
}

type CreatePostMutation struct {
	CreatePost CreatePostMutation_CreatePost "json:\"createPost\" graphql:\"createPost\""
}

func (t *CreatePostMutation) GetCreatePost() *CreatePostMutation_CreatePost {
	if t == nil {
		t = &CreatePostMutation{}
	}
	return &t.CreatePost
}

type CreatePostWithCategoriesMutation struct {
	CreatePostWithCategories CreatePostWithCategoriesMutation_CreatePostWithCategories "json:\"createPostWithCategories\" graphql:\"createPostWithCategories\""
}

func (t *CreatePostWithCategoriesMutation) GetCreatePostWithCategories() *CreatePostWithCategoriesMutation_CreatePostWithCategories {
	if t == nil {
		t = &CreatePostWithCategoriesMutation{}
	}
	return &t.CreatePostWithCategories
}

type UpdatePostMutation struct {
	UpdatePost UpdatePostMutation_UpdatePost "json:\"updatePost\" graphql:\"updatePost\""
}

func (t *UpdatePostMutation) GetUpdatePost() *UpdatePostMutation_UpdatePost {
	if t == nil {
		t = &UpdatePostMutation{}
	}
	return &t.UpdatePost
}

type DeletePostMutation struct {
	DeletePost DeletePostMutation_DeletePost "json:\"deletePost\" graphql:\"deletePost\""
}

func (t *DeletePostMutation) GetDeletePost() *DeletePostMutation_DeletePost {
	if t == nil {
		t = &DeletePostMutation{}
	}
	return &t.DeletePost
}

type RestorePostMutation struct {
	RestorePost *bool "json:\"restorePost,omitempty\" graphql:\"restorePost\""
}

func (t *RestorePostMutation) GetRestorePost() *bool {
	if t == nil {
		t = &RestorePostMutation{}
	}
	return t.RestorePost
}

type GetPostsQuery struct {
	Posts *PostConnectionFields "json:\"posts\" graphql:\"posts\""
}

func (t *GetPostsQuery) GetPosts() *PostConnectionFields {
	if t == nil {
		t = &GetPostsQuery{}
	}
	return t.Posts
}

type GetAllRefreshTokens struct {
	RefreshTokens *RefreshTokenConnectionFields "json:\"refreshTokens\" graphql:\"refreshTokens\""
}

func (t *GetAllRefreshTokens) GetRefreshTokens() *RefreshTokenConnectionFields {
	if t == nil {
		t = &GetAllRefreshTokens{}
	}
	return t.RefreshTokens
}

type DeleteRefreshToken struct {
	DeleteRefreshToken DeleteRefreshToken_DeleteRefreshToken "json:\"deleteRefreshToken\" graphql:\"deleteRefreshToken\""
}

func (t *DeleteRefreshToken) GetDeleteRefreshToken() *DeleteRefreshToken_DeleteRefreshToken {
	if t == nil {
		t = &DeleteRefreshToken{}
	}
	return &t.DeleteRefreshToken
}

type Me struct {
	Me *Me_Me "json:\"me,omitempty\" graphql:\"me\""
}

func (t *Me) GetMe() *Me_Me {
	if t == nil {
		t = &Me{}
	}
	return t.Me
}

const CreatePostMutationDocument = `mutation CreatePostMutation ($input: CreatePostInput!) {
	createPost(input: $input) {
		post {
			... PostFields
		}
	}
}
fragment PostFields on Post {
	id
	title
	link
	content
	moderationComment
	isModerated
	moderatedAt
	deletedAt
	owner {
		id
		displayName
	}
	categories {
		id
		category
	}
}
`

func (c *Client) CreatePostMutation(ctx context.Context, input CreatePostInput, interceptors ...clientv2.RequestInterceptor) (*CreatePostMutation, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreatePostMutation
	if err := c.Client.Post(ctx, "CreatePostMutation", CreatePostMutationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreatePostWithCategoriesMutationDocument = `mutation CreatePostWithCategoriesMutation ($input: CreatePostWithCategoriesInput!) {
	createPostWithCategories(input: $input) {
		post {
			... PostFields
		}
	}
}
fragment PostFields on Post {
	id
	title
	link
	content
	moderationComment
	isModerated
	moderatedAt
	deletedAt
	owner {
		id
		displayName
	}
	categories {
		id
		category
	}
}
`

func (c *Client) CreatePostWithCategoriesMutation(ctx context.Context, input CreatePostWithCategoriesInput, interceptors ...clientv2.RequestInterceptor) (*CreatePostWithCategoriesMutation, error) {
	vars := map[string]any{
		"input": input,
	}

	var res CreatePostWithCategoriesMutation
	if err := c.Client.Post(ctx, "CreatePostWithCategoriesMutation", CreatePostWithCategoriesMutationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdatePostMutationDocument = `mutation UpdatePostMutation ($id: ID!, $input: UpdatePostInput!) {
	updatePost(id: $id, input: $input) {
		post {
			... PostFields
		}
	}
}
fragment PostFields on Post {
	id
	title
	link
	content
	moderationComment
	isModerated
	moderatedAt
	deletedAt
	owner {
		id
		displayName
	}
	categories {
		id
		category
	}
}
`

func (c *Client) UpdatePostMutation(ctx context.Context, id uuid.UUID, input UpdatePostInput, interceptors ...clientv2.RequestInterceptor) (*UpdatePostMutation, error) {
	vars := map[string]any{
		"id":    id,
		"input": input,
	}

	var res UpdatePostMutation
	if err := c.Client.Post(ctx, "UpdatePostMutation", UpdatePostMutationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeletePostMutationDocument = `mutation DeletePostMutation ($id: ID!) {
	deletePost(id: $id) {
		deletedID
	}
}
`

func (c *Client) DeletePostMutation(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*DeletePostMutation, error) {
	vars := map[string]any{
		"id": id,
	}

	var res DeletePostMutation
	if err := c.Client.Post(ctx, "DeletePostMutation", DeletePostMutationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const RestorePostMutationDocument = `mutation RestorePostMutation ($id: ID!) {
	restorePost(id: $id)
}
`

func (c *Client) RestorePostMutation(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*RestorePostMutation, error) {
	vars := map[string]any{
		"id": id,
	}

	var res RestorePostMutation
	if err := c.Client.Post(ctx, "RestorePostMutation", RestorePostMutationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetPostsQueryDocument = `query GetPostsQuery ($first: Int, $after: Cursor, $last: Int, $before: Cursor, $where: PostWhereInput) {
	posts(first: $first, after: $after, last: $last, before: $before, where: $where) {
		... PostConnectionFields
	}
}
fragment PostConnectionFields on PostConnection {
	totalCount
	edges {
		node {
			... PostFields
		}
	}
}
fragment PostFields on Post {
	id
	title
	link
	content
	moderationComment
	isModerated
	moderatedAt
	deletedAt
	owner {
		id
		displayName
	}
	categories {
		id
		category
	}
}
`

func (c *Client) GetPostsQuery(ctx context.Context, first *int64, after *string, last *int64, before *string, where *PostWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetPostsQuery, error) {
	vars := map[string]any{
		"first":  first,
		"after":  after,
		"last":   last,
		"before": before,
		"where":  where,
	}

	var res GetPostsQuery
	if err := c.Client.Post(ctx, "GetPostsQuery", GetPostsQueryDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetAllRefreshTokensDocument = `query GetAllRefreshTokens ($first: Int, $after: Cursor, $last: Int, $before: Cursor, $where: RefreshTokenWhereInput) {
	refreshTokens(first: $first, after: $after, last: $last, before: $before, where: $where) {
		... RefreshTokenConnectionFields
	}
}
fragment RefreshTokenConnectionFields on RefreshTokenConnection {
	totalCount
	pageInfo {
		startCursor
		endCursor
		hasPreviousPage
		hasNextPage
	}
	edges {
		node {
			... RefreshTokenFields
		}
	}
}
fragment RefreshTokenFields on RefreshToken {
	id
	createdAt
	updatedAt
	expiresAt
	revoked
	ipAddress
	userAgent
}
`

func (c *Client) GetAllRefreshTokens(ctx context.Context, first *int64, after *string, last *int64, before *string, where *RefreshTokenWhereInput, interceptors ...clientv2.RequestInterceptor) (*GetAllRefreshTokens, error) {
	vars := map[string]any{
		"first":  first,
		"after":  after,
		"last":   last,
		"before": before,
		"where":  where,
	}

	var res GetAllRefreshTokens
	if err := c.Client.Post(ctx, "GetAllRefreshTokens", GetAllRefreshTokensDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeleteRefreshTokenDocument = `mutation DeleteRefreshToken ($id: ID!) {
	deleteRefreshToken(id: $id) {
		deletedID
	}
}
`

func (c *Client) DeleteRefreshToken(ctx context.Context, id uuid.UUID, interceptors ...clientv2.RequestInterceptor) (*DeleteRefreshToken, error) {
	vars := map[string]any{
		"id": id,
	}

	var res DeleteRefreshToken
	if err := c.Client.Post(ctx, "DeleteRefreshToken", DeleteRefreshTokenDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const MeDocument = `query Me {
	me {
		id
		displayName
	}
}
`

func (c *Client) Me(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*Me, error) {
	vars := map[string]any{}

	var res Me
	if err := c.Client.Post(ctx, "Me", MeDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	CreatePostMutationDocument:               "CreatePostMutation",
	CreatePostWithCategoriesMutationDocument: "CreatePostWithCategoriesMutation",
	UpdatePostMutationDocument:               "UpdatePostMutation",
	DeletePostMutationDocument:               "DeletePostMutation",
	RestorePostMutationDocument:              "RestorePostMutation",
	GetPostsQueryDocument:                    "GetPostsQuery",
	GetAllRefreshTokensDocument:              "GetAllRefreshTokens",
	DeleteRefreshTokenDocument:               "DeleteRefreshToken",
	MeDocument:                               "Me",
}
