name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/setup

  deploy-backend:
    name: Deploy backend
    needs: setup
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout secrets repository
        uses: actions/checkout@v4
        with:
          repository: caliecode/secrets
          path: secrets-repo
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: Copy environment file
        run: |
          cp secrets-repo/la-clipasa/.env .

          if [ -f .env ]; then
            echo ".env file successfully copied from secrets repository"
            echo "Variables included (values hidden):"
            grep -v '^#' .env | cut -d'=' -f1 | sort
          else
            echo "Error: .env file not found!"
            exit 1
          fi

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl secrets import < .env
          flyctl deploy --remote-only --wait-timeout=100
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    concurrency: deploy-group
    name: Deploy frontend
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
