name: Deploy

on:
  push:
    branches:
      - main

jobs:
  setup:
    concurrency: deploy-group
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup

      - name: Checkout secrets repository
        uses: actions/checkout@v4
        with:
          repository: caliecode/secrets
          path: secrets-repo
          token: ${{ secrets.GH_REPO_TOKEN }}

      - name: Copy environment file
        run: |
          cp secrets-repo/la-clipasa/.env .env.prod

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy backend
        run: |
          flyctl secrets import < .env.prod
          flyctl deploy --remote-only --wait-timeout=100
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build frontend
        run: |
          source .envrc

          project build.frontend

      - name: Deploy frontend
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            # pages project list
            pages deploy ./frontend/build
