name: Keepalive

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup

      - name: Run keepalive
        run: |
          npx playwright install-deps chromium
          npx playwright install

          node bin/scripts/keepalive.js
