name: Keepalive

on:
  workflow_dispatch:

  schedule:
    - cron: '0 0 */3 * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: ./.github/actions/setup

      - name: Run keepalive
        run: |
          pnpm --workspace-root i puppeteer
          node bin/scripts/keepalive.js
