name: Tests

env:
  CI: true
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml
